namespace SpriteKind {
    export const Boss = SpriteKind.create()
}
sprites.onOverlap(SpriteKind.Player, SpriteKind.Projectile, function (sprite, otherSprite) {
    if (randint(0, 8) == 1) {
        game.showLongText("Fact 21: Every year, about 1.5 million tons of nitrogen pollution flows into the Gulf of Mexico from the Mississippi River.", DialogLayout.Full)
    } else if (randint(0, 8) == 2) {
        game.showLongText("Fact 22: China and Indonesia are the world’s biggest contributors of plastic pollution in the ocean. Combined, they account for one-third of total ocean pollution.", DialogLayout.Full)
    } else if (randint(0, 8) == 3) {
        game.showLongText("Fact 23: Plastic makes its way to the depths of the ocean. Studies have found that crustaceans in the Marianas Trench, the ocean’s deepest point, have ingested plastic.", DialogLayout.Full)
    } else if (randint(0, 8) == 4) {
        game.showLongText("Fact 24: Approximately one truckload of plastic enters the ocean every single minute.", DialogLayout.Full)
    } else if (randint(0, 8) == 5) {
        game.showLongText("Fact 25: The waste in the ocean takes a long, long time to decompose. Styrofoam takes 80 years, aluminum takes 200 years, and plastic takes 400 years.", DialogLayout.Full)
    } else if (randint(0, 8) == 6) {
        game.showLongText("Fact 26: In some of the most heavily polluted sections of the ocean, plastic outweighs plankton by six times.", DialogLayout.Full)
    } else if (randint(0, 8) == 7) {
        game.showLongText("Fact 27: There’s enough plastic in the ocean to circle the Earth 400 times.", DialogLayout.Full)
    } else if (randint(0, 8) == 8) {
        game.showLongText("Fact 28: Chemicals in heavily polluted waters can make their way back to us and cause serious health issues like reproductive problems, hormonal problems, kidney damage, and nervous system damage", DialogLayout.Full)
    } else {
        game.splash("Hi, who ever is looking at the code, it's currently 3:30am")
    }
    game.gameOver(false)
    game.setGameOverScoringType(game.ScoringType.HighScore)
})
sprites.onOverlap(SpriteKind.Player, SpriteKind.Enemy, function (sprite, otherSprite) {
    if (randint(0, 10) == 1) {
        game.showLongText("Fact 11:Approximately every square mile of ocean has more than 46,000 pieces of plastic floating in it.", DialogLayout.Full)
    } else if (randint(0, 10) == 2) {
        game.showLongText("Fact 12:There are dead zones in the oceans that have been created by pollution making life in those zones impossible for marine or plant life.", DialogLayout.Full)
    } else if (randint(0, 10) == 3) {
        game.showLongText("Fact 13:Over 100,000 marine animals die every year from plastic entanglement and ingestion.", DialogLayout.Full)
    } else if (randint(0, 10) == 4) {
        game.showLongText("Fact 14: Carbon emissions harm the oceans as well as the air. If our behavior continues as is, the surface water of the ocean could be 150% more acidic than it is now.", DialogLayout.Full)
    } else if (randint(0, 10) == 5) {
        game.showLongText("Fact 15: Not all sewage that enters the ocean is treated. 80% of sewage that flows into the Mediterranean Sea is untreated, which can lead to disease.", DialogLayout.Full)
    } else if (randint(0, 10) == 6) {
        game.showLongText("Fact 16: Oil spills only contribute to 12% of the oil in the ocean. 36% of the oil comes from runoff sources from cities and companies.", DialogLayout.Full)
    } else if (randint(0, 10) == 7) {
        game.showLongText("Fact 17: Ocean noise pollution is an issue, too. Ships, tankers, and shipping containers emit sounds like high-intensity sonar and air guns. This noise pollution injures fish, disrupts their habitats, and more.", DialogLayout.Full)
    } else if (randint(0, 10) == 8) {
        game.showLongText("Fact 18: Over one-third of the Atlantic ocean that shellfish live in is negatively impacted by pollution. This adversely affects the shellfish businesses on the East Coast.", DialogLayout.Full)
    } else if (randint(0, 10) == 9) {
        game.showLongText("Fact 19: It’s estimated that by the year 2050, there will be more plastic in the ocean than fish (by weight).", DialogLayout.Full)
    } else if (randint(0, 10) == 10) {
        game.showLongText("Fact 20: Fish and other marine life often can’t tell the difference between plastic and food. If the animal eats plastic, they can’t digest it. The plastic fills their stomachs, so they starve to death.", DialogLayout.Full)
    } else {
        game.splash("Hi, who ever is looking at the code, it's currently 3:30am")
    }
    game.gameOver(false)
    game.setGameOverScoringType(game.ScoringType.HighScore)
})
let projectile: Sprite = null
game.showLongText("Every day ~8 million pieces of trash end up in our oceans each day. This trash can poision our wildlife and is slowly reducing the biodiversity of our oceans. Let's see what being a fish in a modern day ocean. Use WASD or the arrow keys to move.  ", DialogLayout.Full)
info.setScore(0)
scene.setBackgroundImage(assets.image`myImage`)
let Fish = sprites.create(img`
    . . . . . . . . . . . . . . . . 
    . . . . . . . . c c c c . . . . 
    . . . . . . c c d d d d c . . . 
    . . . . . c c c c c c d c . . . 
    . . . . c c 4 4 4 4 d c c . . . 
    . . . c 4 d 4 4 4 4 4 1 c . c c 
    . . c 4 4 4 1 4 4 4 4 d 1 c 4 c 
    . c 4 4 4 4 1 4 4 4 4 4 1 c 4 c 
    f 4 4 4 4 4 1 4 4 4 4 4 1 4 4 f 
    f 4 4 4 f 4 1 c c 4 4 4 1 f 4 f 
    f 4 4 4 4 4 1 4 4 f 4 4 d f 4 f 
    . f 4 4 4 4 1 c 4 f 4 d f f f f 
    . . f f 4 d 4 4 f f 4 c f c . . 
    . . . . f f 4 4 4 4 c d b c . . 
    . . . . . . f f f f d d d c . . 
    . . . . . . . . . . c c c . . . 
    `, SpriteKind.Player)
controller.moveSprite(Fish, 100, 100)
let Bottle_1 = sprites.create(assets.image`Bottle 1`, SpriteKind.Enemy)
let Bottle_2 = sprites.create(img`
    ....................
    ....................
    ....................
    ....................
    ....................
    ....................
    .....7977777777.....
    .....7777777777.....
    ......66666666......
    ......99999999......
    .....9999999999.....
    .....9999999999.....
    .....9999999999.....
    .....7777777777.....
    .....7777777777.....
    .....7777777776.....
    .....7777777776.....
    ......76666666......
    ....................
    ....................
    `, SpriteKind.Enemy)
let Bottle_3 = sprites.create(img`
    ....................
    ....................
    ....................
    ....................
    ....................
    ....................
    ........4eee........
    .......eeeeee.......
    .........cc.........
    .........4c.........
    ........4444........
    .......444444.......
    ......44444444......
    .....4444444444.....
    .....eeeeeeeeee.....
    .....eeeeeeeecc.....
    ......eeeeeecc......
    .......eccccc.......
    ....................
    ....................
    `, SpriteKind.Enemy)
let Bottle_4 = sprites.create(img`
    ....................
    ....................
    ....................
    ....................
    ....................
    ....................
    ........dd55........
    ........5555........
    .........44.........
    ........dddd........
    ........dddd........
    .......dddddd.......
    .......dddddd.......
    .......dddddd.......
    .......dddddd.......
    .......dddddd.......
    .......dddddd.......
    ........dddd........
    ........4444........
    ....................
    `, SpriteKind.Enemy)
let Bottle_5 = sprites.create(img`
    ....................
    ....................
    ....................
    ....................
    ....................
    ....................
    .........888........
    .........888........
    ......888888888.....
    ........fffff.......
    .......8888888......
    .......8998888......
    .......8988888......
    .......8888888......
    .......8888888......
    .......8888888......
    ......888888888.....
    ......fffffffff.....
    ....................
    ....................
    `, SpriteKind.Enemy)
Bottle_1.setPosition(randint(5, 160), 0)
Bottle_1.setVelocity(0, randint(1, 100))
Bottle_2.setPosition(0, 0)
Bottle_3.setPosition(0, 0)
Bottle_4.setPosition(0, 0)
Bottle_5.setPosition(0, 0)
animation.runImageAnimation(
Fish,
[img`
    . . . . . . . . . . . . . . . . 
    . . . . . . . . c c c c . . . . 
    . . . . . . c c d d d d c . . . 
    . . . . . c c c c c c d c . . . 
    . . . . c c 4 4 4 4 d c c . . . 
    . . . c 4 d 4 4 4 4 4 1 c . c c 
    . . c 4 4 4 1 4 4 4 4 d 1 c 4 c 
    . c 4 4 4 4 1 4 4 4 4 4 1 c 4 c 
    f 4 4 4 4 4 1 4 4 4 4 4 1 4 4 f 
    f 4 4 4 f 4 1 c c 4 4 4 1 f 4 f 
    f 4 4 4 4 4 1 4 4 f 4 4 d f 4 f 
    . f 4 4 4 4 1 c 4 f 4 d f f f f 
    . . f f 4 d 4 4 f f 4 c f c . . 
    . . . . f f 4 4 4 4 c d b c . . 
    . . . . . . f f f f d d d c . . 
    . . . . . . . . . . c c c . . . 
    `,img`
    . . . . . . . . . . . . . . . . 
    . . . . . . . c c c c c . . . . 
    . . . . . . c d d d d d c . . . 
    . . . . . . c c c c c d c . . . 
    . . . . . c 4 4 4 4 d c c . . . 
    . . . . c d 4 4 4 4 4 1 c . . . 
    . . . c 4 4 1 4 4 4 4 4 1 c . . 
    . . c 4 4 4 4 1 4 4 4 4 1 c c c 
    . c 4 4 4 4 4 1 c c 4 4 1 4 4 c 
    . c 4 4 4 4 4 1 4 4 f 4 1 f 4 f 
    f 4 4 4 4 f 4 1 c 4 f 4 d f 4 f 
    f 4 4 4 4 4 4 1 4 f f 4 f f 4 f 
    . f 4 4 4 4 1 4 4 4 4 c b c f f 
    . . f f f d 4 4 4 4 c d d c . . 
    . . . . . f f f f f c c c . . . 
    . . . . . . . . . . . . . . . . 
    `,img`
    . . . . . . . . c c c c . . . . 
    . . . . . . c c d d d d c . . . 
    . . . . . c c c c c c d c . . . 
    . . . . c c 4 4 4 4 d c c . c c 
    . . . c 4 d 4 4 4 4 4 1 c c 4 c 
    . . c 4 4 4 1 4 4 4 4 d 1 c 4 f 
    . c 4 4 4 4 1 4 4 4 4 4 1 4 4 f 
    f 4 4 4 4 4 1 1 c f 4 4 1 f 4 f 
    f 4 4 4 f 4 1 c 4 f 4 4 1 f 4 f 
    f 4 4 4 4 4 1 4 4 f 4 4 d f f f 
    . f 4 4 4 4 1 c c 4 4 d f f . . 
    . . f f 4 d 4 4 4 4 4 c f . . . 
    . . . . f f 4 4 4 4 c d b c . . 
    . . . . . . f f f f d d d c . . 
    . . . . . . . . . . c c c . . . 
    . . . . . . . . . . . . . . . . 
    `,img`
    . . . . . . . . . . . . . . . . 
    . . . . . . . . . c c c c . . . 
    . . . . . . . c c d d d d c . . 
    . . . . . c c c c c c d d c . . 
    . . . c c c 4 4 4 4 d c c c c c 
    . . c 4 4 1 4 4 4 4 4 1 c c 4 f 
    . c 4 4 4 4 1 4 4 4 4 d 1 f 4 f 
    f 4 4 4 4 4 1 4 4 4 4 4 1 f 4 f 
    f 4 4 f 4 4 1 4 c f 4 4 1 4 4 f 
    f 4 4 4 4 4 1 c 4 f 4 4 1 f f f 
    . f 4 4 4 4 1 4 4 f 4 4 d f . . 
    . . f 4 4 1 4 c c 4 4 d f . . . 
    . . . f d 4 4 4 4 4 4 c f . . . 
    . . . . f f 4 4 4 4 c d b c . . 
    . . . . . . f f f f d d d c . . 
    . . . . . . . . . . c c c . . . 
    `],
150,
true
)
game.onUpdateInterval(5000, function () {
    if (info.score() >= 10) {
        if (randint(1, 10) <= 5) {
            projectile = sprites.createProjectileFromSide(img`
                ..............fffcc.............
                ..............fcbddcc...........
                ...............fbbddcc..........
                ...............fcbbccf..........
                ..ccc.........ffccccccfffff.....
                ..cbbcc....fffcbbbbcbbbbbbbff...
                ...cbbdc.ffcccbbbbcbcbbbbbbbbf..
                ...fbbdcfcccccbbbcbcbbffbbbbbbff
                ....fbbffcccccbbbbbcb1ff11bbbcbf
                ....fcbbcccccccbbbbb11111111bbbf
                ....fcccccccccccbbbb11cc33111bf.
                ...fcbbffbdbcccccbbb111c13cccf..
                ...fbbf..ccddddcfbbbc111c31cf...
                ..fbbf.....ccdccbbdbf111cccf....
                ..fff........ccbbdcfcccc........
                ..............fffff.............
                `, randint(10, 100), 0)
            projectile.setPosition(0, randint(0, 160))
            animation.runImageAnimation(
            projectile,
            [img`
                ..............fffcc.............
                ..............fcbddcc...........
                ...............fbbddcc..........
                ...............fcbbccf..........
                ..ccc.........ffccccccfffff.....
                ..cbbcc....fffcbbbbcbbbbbbbff...
                ...cbbdc.ffcccbbbbcbcbbbbbbbbf..
                ...fbbdcfcccccbbbcbcbbffbbbbbbff
                ....fbbffcccccbbbbbcb1ff11bbbcbf
                ....fcbbcccccccbbbbb11111111bbbf
                ....fcccccccccccbbbb11cc33111bf.
                ...fcbbffbdbcccccbbb111c13cccf..
                ...fbbf..ccddddcfbbbc111c31cf...
                ..fbbf.....ccdccbbdbf111cccf....
                ..fff........ccbbdcfcccc........
                ..............fffff.............
                `,img`
                ..............fffcc.............
                ..............fbbddc............
                ...............fbbddc...........
                ccc............fcbbccf..........
                cbbcc.........ffccccccffffff....
                .cbbdc.....fffcbbbbbbbbbbbbbff..
                .fbbddc..ffcccbbbbcbcbbbbbbbbbff
                ..fbbdfffcccccbbbcbcbbffbbbbbcbf
                ..fcbbbcccccccbbbcbcb1ff1111bbbf
                ..fccbcccccccccbbbbbb11111111bf.
                .fcbbfffccccccccbbbb11cc33cccf..
                .fbbf...cbdbcccccbbb111c131cf...
                fbbf.....ccdddddfbbbc111c33f....
                fff........ccddfbbdbf1111ff.....
                .............cfbbdbfccccc.......
                ..............fffff.............
                `,img`
                ..............fffc..............
                ..............fbddcc............
                ..ccc.........ffbddbc...........
                ..cbbc.........fcbbccf..........
                ...cbdc.......ffccccccfffffff...
                ...fbdc....fffcbbbbbbbbbbbbbcff.
                ....fbdc.ffcccbbbbbbcbbbbbbbbbcf
                ....fcdffcccccbbbcbcbbbffbbbbcbf
                ....fcbbccccccbbbcbcbbbff1111bbf
                ...fcbbccccccccbbbcbb11111111bf.
                ...fbbfffcccccccbbbb11bc33cccf..
                ..fbbf..cbdbcccccbbb111c131cf...
                ..fff....cbdddddccbbc111c33f....
                ..........ccbddccbbdf1111ff.....
                ............ccfbbbdfccccc.......
                ..............fffff.............
                `,img`
                ..............fffcc.............
                ..............fbbddc............
                ...............fbbddc...........
                ccc............fcbbccf..........
                cbbcc.........ffccccccffffff....
                .cbbdc.....fffcbbbbbbbbbbbbbff..
                .fbbddc..ffcccbbbbcbcbbbbbbbbbff
                ..fbbdfffcccccbbbcbcbbffbbbbbcbf
                ..fcbbbcccccccbbbcbcb1ff1111bbbf
                ..fccbcccccccccbbbbbb11111111bf.
                .fcbbfffccccccccbbbb11cc33cccf..
                .fbbf...cbdbcccccbbb111c131cf...
                fbbf.....ccdddddfbbbc111c33f....
                fff........ccddfbbdbf1111ff.....
                .............cfbbdbfccccc.......
                ..............fffff.............
                `],
            150,
            true
            )
        }
        if (randint(1, 10) <= 5) {
            projectile = sprites.createProjectileFromSide(img`
                ..............fffcc.............
                ..............fcbddcc...........
                ...............fbbddcc..........
                ...............fcbbccf..........
                ..ccc.........ffccccccfffff.....
                ..cbbcc....fffcbbbbcbbbbbbbff...
                ...cbbdc.ffcccbbbbcbcbbbbbbbbf..
                ...fbbdcfcccccbbbcbcbbffbbbbbbff
                ....fbbffcccccbbbbbcb1ff11bbbcbf
                ....fcbbcccccccbbbbb11111111bbbf
                ....fcccccccccccbbbb11cc33111bf.
                ...fcbbffbdbcccccbbb111c13cccf..
                ...fbbf..ccddddcfbbbc111c31cf...
                ..fbbf.....ccdccbbdbf111cccf....
                ..fff........ccbbdcfcccc........
                ..............fffff.............
                `, randint(10, 100), 0)
            projectile.setPosition(0, randint(0, 160))
            animation.runImageAnimation(
            projectile,
            [img`
                ..............fffcc.............
                ..............fcbddcc...........
                ...............fbbddcc..........
                ...............fcbbccf..........
                ..ccc.........ffccccccfffff.....
                ..cbbcc....fffcbbbbcbbbbbbbff...
                ...cbbdc.ffcccbbbbcbcbbbbbbbbf..
                ...fbbdcfcccccbbbcbcbbffbbbbbbff
                ....fbbffcccccbbbbbcb1ff11bbbcbf
                ....fcbbcccccccbbbbb11111111bbbf
                ....fcccccccccccbbbb11cc33111bf.
                ...fcbbffbdbcccccbbb111c13cccf..
                ...fbbf..ccddddcfbbbc111c31cf...
                ..fbbf.....ccdccbbdbf111cccf....
                ..fff........ccbbdcfcccc........
                ..............fffff.............
                `,img`
                ..............fffcc.............
                ..............fbbddc............
                ...............fbbddc...........
                ccc............fcbbccf..........
                cbbcc.........ffccccccffffff....
                .cbbdc.....fffcbbbbbbbbbbbbbff..
                .fbbddc..ffcccbbbbcbcbbbbbbbbbff
                ..fbbdfffcccccbbbcbcbbffbbbbbcbf
                ..fcbbbcccccccbbbcbcb1ff1111bbbf
                ..fccbcccccccccbbbbbb11111111bf.
                .fcbbfffccccccccbbbb11cc33cccf..
                .fbbf...cbdbcccccbbb111c131cf...
                fbbf.....ccdddddfbbbc111c33f....
                fff........ccddfbbdbf1111ff.....
                .............cfbbdbfccccc.......
                ..............fffff.............
                `,img`
                ..............fffc..............
                ..............fbddcc............
                ..ccc.........ffbddbc...........
                ..cbbc.........fcbbccf..........
                ...cbdc.......ffccccccfffffff...
                ...fbdc....fffcbbbbbbbbbbbbbcff.
                ....fbdc.ffcccbbbbbbcbbbbbbbbbcf
                ....fcdffcccccbbbcbcbbbffbbbbcbf
                ....fcbbccccccbbbcbcbbbff1111bbf
                ...fcbbccccccccbbbcbb11111111bf.
                ...fbbfffcccccccbbbb11bc33cccf..
                ..fbbf..cbdbcccccbbb111c131cf...
                ..fff....cbdddddccbbc111c33f....
                ..........ccbddccbbdf1111ff.....
                ............ccfbbbdfccccc.......
                ..............fffff.............
                `,img`
                ..............fffcc.............
                ..............fbbddc............
                ...............fbbddc...........
                ccc............fcbbccf..........
                cbbcc.........ffccccccffffff....
                .cbbdc.....fffcbbbbbbbbbbbbbff..
                .fbbddc..ffcccbbbbcbcbbbbbbbbbff
                ..fbbdfffcccccbbbcbcbbffbbbbbcbf
                ..fcbbbcccccccbbbcbcb1ff1111bbbf
                ..fccbcccccccccbbbbbb11111111bf.
                .fcbbfffccccccccbbbb11cc33cccf..
                .fbbf...cbdbcccccbbb111c131cf...
                fbbf.....ccdddddfbbbc111c33f....
                fff........ccddfbbdbf1111ff.....
                .............cfbbdbfccccc.......
                ..............fffff.............
                `],
            150,
            true
            )
        }
        if (randint(1, 10) <= 5) {
            projectile = sprites.createProjectileFromSide(img`
                ..............fffcc.............
                ..............fcbddcc...........
                ...............fbbddcc..........
                ...............fcbbccf..........
                ..ccc.........ffccccccfffff.....
                ..cbbcc....fffcbbbbcbbbbbbbff...
                ...cbbdc.ffcccbbbbcbcbbbbbbbbf..
                ...fbbdcfcccccbbbcbcbbffbbbbbbff
                ....fbbffcccccbbbbbcb1ff11bbbcbf
                ....fcbbcccccccbbbbb11111111bbbf
                ....fcccccccccccbbbb11cc33111bf.
                ...fcbbffbdbcccccbbb111c13cccf..
                ...fbbf..ccddddcfbbbc111c31cf...
                ..fbbf.....ccdccbbdbf111cccf....
                ..fff........ccbbdcfcccc........
                ..............fffff.............
                `, randint(10, 100), 0)
            projectile.setPosition(0, randint(0, 160))
            animation.runImageAnimation(
            projectile,
            [img`
                ..............fffcc.............
                ..............fcbddcc...........
                ...............fbbddcc..........
                ...............fcbbccf..........
                ..ccc.........ffccccccfffff.....
                ..cbbcc....fffcbbbbcbbbbbbbff...
                ...cbbdc.ffcccbbbbcbcbbbbbbbbf..
                ...fbbdcfcccccbbbcbcbbffbbbbbbff
                ....fbbffcccccbbbbbcb1ff11bbbcbf
                ....fcbbcccccccbbbbb11111111bbbf
                ....fcccccccccccbbbb11cc33111bf.
                ...fcbbffbdbcccccbbb111c13cccf..
                ...fbbf..ccddddcfbbbc111c31cf...
                ..fbbf.....ccdccbbdbf111cccf....
                ..fff........ccbbdcfcccc........
                ..............fffff.............
                `,img`
                ..............fffcc.............
                ..............fbbddc............
                ...............fbbddc...........
                ccc............fcbbccf..........
                cbbcc.........ffccccccffffff....
                .cbbdc.....fffcbbbbbbbbbbbbbff..
                .fbbddc..ffcccbbbbcbcbbbbbbbbbff
                ..fbbdfffcccccbbbcbcbbffbbbbbcbf
                ..fcbbbcccccccbbbcbcb1ff1111bbbf
                ..fccbcccccccccbbbbbb11111111bf.
                .fcbbfffccccccccbbbb11cc33cccf..
                .fbbf...cbdbcccccbbb111c131cf...
                fbbf.....ccdddddfbbbc111c33f....
                fff........ccddfbbdbf1111ff.....
                .............cfbbdbfccccc.......
                ..............fffff.............
                `,img`
                ..............fffc..............
                ..............fbddcc............
                ..ccc.........ffbddbc...........
                ..cbbc.........fcbbccf..........
                ...cbdc.......ffccccccfffffff...
                ...fbdc....fffcbbbbbbbbbbbbbcff.
                ....fbdc.ffcccbbbbbbcbbbbbbbbbcf
                ....fcdffcccccbbbcbcbbbffbbbbcbf
                ....fcbbccccccbbbcbcbbbff1111bbf
                ...fcbbccccccccbbbcbb11111111bf.
                ...fbbfffcccccccbbbb11bc33cccf..
                ..fbbf..cbdbcccccbbb111c131cf...
                ..fff....cbdddddccbbc111c33f....
                ..........ccbddccbbdf1111ff.....
                ............ccfbbbdfccccc.......
                ..............fffff.............
                `,img`
                ..............fffcc.............
                ..............fbbddc............
                ...............fbbddc...........
                ccc............fcbbccf..........
                cbbcc.........ffccccccffffff....
                .cbbdc.....fffcbbbbbbbbbbbbbff..
                .fbbddc..ffcccbbbbcbcbbbbbbbbbff
                ..fbbdfffcccccbbbcbcbbffbbbbbcbf
                ..fcbbbcccccccbbbcbcb1ff1111bbbf
                ..fccbcccccccccbbbbbb11111111bf.
                .fcbbfffccccccccbbbb11cc33cccf..
                .fbbf...cbdbcccccbbb111c131cf...
                fbbf.....ccdddddfbbbc111c33f....
                fff........ccddfbbdbf1111ff.....
                .............cfbbdbfccccc.......
                ..............fffff.............
                `],
            150,
            true
            )
        }
    }
})
forever(function () {
    if (info.score() == 5) {
        Bottle_2.setPosition(randint(5, 160), 0)
        Bottle_2.setVelocity(0, randint(50, 100))
        pauseUntil(() => info.score() == 6)
    }
    if (info.score() == 6) {
        Bottle_3.setPosition(randint(5, 160), 0)
        Bottle_3.setVelocity(0, randint(50, 100))
        pauseUntil(() => info.score() == 7)
    }
    if (info.score() == 7) {
        Bottle_4.setPosition(randint(5, 160), 0)
        Bottle_4.setVelocity(0, randint(50, 100))
        pauseUntil(() => info.score() == 8)
        if (info.score() == 9) {
            Bottle_5.setPosition(randint(5, 160), 0)
            Bottle_5.setVelocity(0, randint(50, 100))
            pauseUntil(() => info.score() == 10)
        }
    }
})
forever(function () {
    if (Fish.y < 0 || (Fish.x < 0 || (Fish.x > 160 || Fish.y > 120))) {
        if (randint(0, 10) == 1) {
            game.showLongText("Fact:1Plastics are the most common element found in the ocean today. Plastic, in particular, is harmful to the environment as it does not break down easily and is often mistaken as food by marine animals.", DialogLayout.Full)
        } else if (randint(0, 10) == 2) {
            game.showLongText("Fact 2:According to a study done by the University of Georgia, 18 billion pounds of plastic trash winds up in our oceans each year. To put that in perspective, it’s enough trash to cover every foot of coastline around the world with five full trash bags of plastic…compounding every year.", DialogLayout.Full)
        } else if (randint(0, 10) == 3) {
            game.showLongText("Fact 3:The 5 most common items found in coastal cleanups around the world are all single-use plastics. They are: plastic cigarette butts, food wrappers, plastic beverage bottles, plastic bottle caps, and plastic straws and drink stirrers.", DialogLayout.Full)
        } else if (randint(0, 10) == 4) {
            game.showLongText("Fact 4:There are 5.25 trillion pieces of plastic debris in the ocean. Of that, 269,000 tons float on the surface, while some four billion plastic microfibers per square kilometer litter the deep sea.", DialogLayout.Full)
        } else if (randint(0, 10) == 5) {
            game.showLongText("Fact 5:80% of trash in the ocean is from land-based sources, including individuals, industry and improper waste management/infrastructure. Only 20% is the result of ocean-based sources, such as the fishing, shipping, and cruise ship industries.", DialogLayout.Full)
        } else if (randint(0, 10) == 6) {
            game.showLongText("Fact 6:Plastics cause more than 80% of the negative effects on animals associated with ocean trash.", DialogLayout.Full)
        } else if (randint(0, 10) == 7) {
            game.showLongText("Fact 7:There is an island of garbage twice the size of Texas inside the Pacific Ocean: the North Pacific Gyre off the coast of California is the largest oceanic garbage site in the entire world. It’s here that the number of floating plastic pieces in the water outnumbers total marine life six to one in the immediate vicinity.", DialogLayout.Full)
        } else if (randint(0, 10) == 8) {
            game.showLongText("Fact 8: Ocean pollutions kills more than one million sea birds each year.", DialogLayout.Full)
        } else if (randint(0, 10) == 9) {
            game.showLongText("Fact 9:A recent survey found ocean pollution is more common in deep waters (more than 2,000 feet deep), with the most common offenders being plastic bags, metal cans, fishing equipment, glass bottles, shoes, and tires.", DialogLayout.Full)
        } else if (randint(0, 10) == 10) {
            game.showLongText("Fact 10:Research estimates anywhere from 15 to 51 trillion particles of floating micro plastic are in our oceans, weighing between 205-520 million pounds. This includes plastic microbeads (used as exfoliates in some personal care products) and synthetic fibers, both of which are too small to be filtered out by many waste water treatment plants.", DialogLayout.Full)
        } else {
            game.splash("Hi, who ever is looking at the code, it's currently 3:30am")
        }
        game.gameOver(false)
        game.setGameOverScoringType(game.ScoringType.HighScore)
    }
})
game.onUpdateInterval(500, function () {
    if (Bottle_1.y > 120) {
        if (info.score() <= 5) {
            Bottle_1.setPosition(randint(0, 160), 0)
            Bottle_1.setVelocity(0, 100)
            info.changeScoreBy(1)
        } else {
            Bottle_1.setPosition(randint(0, 160), 0)
            Bottle_1.setVelocity(0, randint(1, 100))
            info.changeScoreBy(1)
        }
    }
    if (info.score() >= 5) {
        if (Bottle_2.y > 120) {
            Bottle_2.setPosition(randint(0, 160), 0)
            Bottle_2.setVelocity(0, randint(1, 100))
            info.changeScoreBy(1)
        }
        if (Bottle_3.y > 120) {
            Bottle_3.setPosition(randint(0, 160), 0)
            Bottle_3.setVelocity(0, randint(1, 100))
            info.changeScoreBy(1)
        }
        if (Bottle_4.y > 120) {
            Bottle_4.setPosition(randint(0, 160), 0)
            Bottle_4.setVelocity(0, randint(1, 100))
            info.changeScoreBy(1)
        }
        if (Bottle_5.y > 120) {
            Bottle_5.setPosition(randint(0, 160), 0)
            Bottle_5.setVelocity(0, randint(1, 100))
            info.changeScoreBy(1)
        }
    }
})
